# Configurações de Energia e Sono
# O teclado dorme após 1 hora (1*60*60*1000ms)
CONFIG_ZMK_SLEEP=y
CONFIG_ZMK_IDLE_SLEEP_TIMEOUT=3600000

# DESATIVAR ZMK STUDIO (Causa erro de build no Corne 6-col)
CONFIG_ZMK_STUDIO=n

# DESATIVAR ENCODER (Você não tem o hardware do Eyelash)
CONFIG_EC11=n
CONFIG_EC11_TRIGGER_GLOBAL_THREAD=n

# Mouse e Pointing (Pode manter se usar as teclas de mouse no keymap)
CONFIG_ZMK_POINTING=y

# Bluetooth e Conectividade
CONFIG_BT_CTLR_TX_PWR_PLUS_8=y
CONFIG_ZMK_HID_REPORT_TYPE_NKRO=n

# Display do Dongle
CONFIG_ZMK_DISPLAY=y
CONFIG_ZMK_DONGLE_DISPLAY_DONGLE_BATTERY=y

# Debounce (Melhora a resposta das teclas)
CONFIG_ZMK_KSCAN_DEBOUNCE_PRESS_MS=8
CONFIG_ZMK_KSCAN_DEBOUNCE_RELEASE_MS=8
